application: line-bot-159514
version: 1
runtime: go
api_version: go1

env_variables:
  LINE_API_SECRET: 'LINE_API_SECRET'
  LINE_API_TOKEN: 'LINE_API_TOKEN'

handlers:

- url: /img
  static_dir: static/img/

- url: /.*
  script: _go_app
